const data = [
  {
    display: require("./assets/images/sri.jpg"),
    greeting: "Srinidhi",
    wish: "Click for a recap of one year that feels like half.",
    name: "Dear minu babi bb babeh bhubber bbrrr b-",
    canvaLink: "https://www.canva.com/design/DAE1Q-bXTZo/view?embed",
    song: new Audio(require("./assets/sounds/sri.mp3")),
  },
  {
    display: require("./assets/images/kush.png"),
    greeting: "Kush",
    name: "Dear munnu",
    wish: "Click here for more munnu, and a little bit of chunnu",
    canvaLink: "https://www.canva.com/design/DAE1aZ1AcG4/view?embed",
    song: new Audio(require("./assets/sounds/kush.mp3")),
  },
  {
    display: require("./assets/images/anitej.png"),
    greeting: "Anitej",
    wish: "Click here to get ice cream on your face",
    name: "Dear Mrinal",
    canvaLink: "https://www.canva.com/design/DAE1Z0AjMc4/view?embed",
    song: new Audio(require("./assets/sounds/anitej.mp3")),
  },
  {
    display: require("./assets/images/mridul.jpeg"),
    greeting: "Mrudul",
    wish: "pvt roomie time 🥰 all others look away 😡",
    canvaLink: "https://www.canva.com/design/DAE1bnRCwSU/view?embed",
    song: new Audio(require("./assets/sounds/mridul.mp3")),
  },
  {
    display: require("./assets/images/sam.jpeg"),
    greeting: "Bhoskar",
    canvaLink: "https://www.canva.com/design/DAE1UUh0wrI/view?embed",
    wish: "Tap to cum inside",
    name: "Dear thokar",
    song: new Audio(require("./assets/sounds/sam.mp3")),
  },
  {
    display: require("./assets/images/daman.jpeg"),
    greeting: "Behroopiya",
    wish: "Agar tune galat guess kiya to tune ekdum hagg diya",
    song: new Audio(require("./assets/sounds/daman.mp3")),
    canvaLink: "https://www.canva.com/design/DAE1cf3bLUI/view?embed",
  },
  {
    display: require("./assets/images/baddo.jpeg"),
    greeting: "Baddo",
    wish: "I fell for you on those lazy sunny afternoons in ara garden ♥️",
    name: "Dear mrunal thaggur",
    canvaLink: "https://www.canva.com/design/DAE1Vs7WcUs/view?embed",
    song: new Audio(require("./assets/sounds/baddo.mp3")),
  },
  {
    display: require("./assets/images/ishika.jpeg"),
    greeting: "Ishika",
    wish: "Click here and kindly don’t revert",
    name: "",
    canvaLink: "https://www.canva.com/design/DAE1UuavyzU/view?embed",
    song: new Audio(require("./assets/sounds/ishika.mp3")),
  },
  {
    display: require("./assets/images/kas.jpeg"),
    greeting: "Kasvi",
    wish: "Click for handmade goodies",
    name: "",
    canvaLink: "https://www.canva.com/design/DAE1V7WSFl8/view?embed",
    song: new Audio(require("./assets/sounds/kasvi.mp3")),
  },
  {
    display: require("./assets/images/shivang.jpeg"),
    greeting: "Shivang",
    wish: "Happy birthday! Hope you have a great year ahead. Here’s to more parties and trips with you ❤️",
    name: "",
    canvaLink: "https://www.canva.com/design/DAE1WhIavts/view?embed",
    song: new Audio(require("./assets/sounds/shivang.mp3")),
  },
  {
    display: require("./assets/images/maria.jpeg"),
    greeting: "Maria",
    wish: "Click here for a reminder of how many 21 parties you attended",
    name: "",
    canvaLink: "https://www.canva.com/design/DAE1UbNQjTU/view?embed",
    song: new Audio(require("./assets/sounds/maria.mp3")),
  },
  {
    display: require("./assets/images/gayatri.jpeg"),
    greeting: "Gayatri",
    wish: " ",
    name: "4:44",
    canvaLink: "https://www.canva.com/design/DAE1aMPv76s/view?embed",
    song: new Audio(require("./assets/sounds/gayatri.mp3")),
  },
  {
    display: require("./assets/images/ridhi.gif"),
    greeting: "Riddhi",
    wish: "Forg",
    name: "Dear Mrinu",
    canvaLink: "https://www.canva.com/design/DAE1fRH3BHg/view?embed",
    song: new Audio(require("./assets/sounds/riddhi.mp3")),
  },
  {
    display: require("./assets/images/nishat.jpeg"),
    greeting: "Nishat",
    name: "10 rupay ki pepsi mera bhai sabse sexy",
    wish: "happy birthday to you!",
    canvaLink: "https://www.canva.com/design/DAE1g-KdtbU/view?embed",
    song: new Audio(require("./assets/sounds/nishat.mp3")),
  },
  {
    display: require("./assets/images/kaustabh.jpeg"),
    greeting: "Kaustabh",
    wish: "Happy birthday thakur",
    canvaLink: "https://www.canva.com/design/DAE1fvTBQmw/view?embed",
    song: new Audio(require("./assets/sounds/kaustabh.mp3")),
  },
  {
    display: require("./assets/images/pranav.jpeg"),
    greeting: "Pranav",
    wish: "If you didn't exist, I probably would've been straight. Happy Birthday Jaanuuuu, mera Shona, mera Babu, mera bhosda",
    vid: require("./assets/images/pranav.mp4"),
  },
  {
    display: require("./assets/images/karthik.jpeg"),
    greeting: "Karthik Ram",
    vid: require("./assets/images/karthik.mp4"),
  },
  {
    display: require("./assets/images/ritvik.jpeg"),
    greeting: "Ritvik",
    wish: "If you didn't exist, Mary Thomas wouldn't have left us and duniya me gyaan chodne waale kam log hote.",
    vid: require("./assets/images/ritvik.mp4"),
  },
  {
    display: require("./assets/images/tanya.jpeg"),
    greeting: "Tanya",
    wish: " ",
    xoxo: false,
    name: "If u didn’t exist, I’d not have a permanent HUL partner (& also not a perfect 3rd roomie). Thank u for the selfies of u & Anitej cuddling at parties. Here’s to (unsuccessfully) fighting with miss Anishya for the sake of people who need our services. HBD!! 💙",
    openable: false,
  },
  {
    display: require("./assets/images/amogh.jpeg"),
    greeting: "Amogh",
    wish: " ",
    name: "not very good at writing birthday messages, so this is an attempt 💀. Always had fun in our talks & all ur help in placements & BTP. u are always a great person to talk to. happy to have gotten to interact more in goa. loved lying on the floor of LPK & getting mommied by Manoj.",
    xoxo: false,
    openable: false,
  },
  {
    display: require("./assets/images/dheerja.jpeg"),
    greeting: "Dheerja",
    name: "Happy bday Mrinuuu❤️",
    wish: "Thank you for existing and making my roomie the happiest! Mil lo usse jaldiiii😂 also looking forward to vibing on honey singh songs sometime again soon!!!!",
    openable: false,
  },
  {
    display: require("./assets/images/lj.jpeg"),
    greeting: "Ujjwal",
    name: "Yo Mrinal",
    wish: "One of the best people to play the drums that I've known (or rather who knows me🥴) in the last few years. But even more than that, you're a gem of a guy. Kya hi fun launda hai bhai tu. Need to do lots of गढमस्ती ASAP🔥",
    openable: false,
    xoxo: false,
  },
  {
    display: require("./assets/images/jc.jpeg"),
    greeting: "JC",
    wish: "happy birthday boiiii!! U is a cutie gud & softboi, let's dhoom dhaam asap 😉",
    name: "",
    openable: false,
  },
  {
    display: require("./assets/images/aradhya.jpeg"),
    greeting: "Aradhya",
    wish: "No text required picture says it all. 😩👍",
    openable: false,
  },
];

export default data;
